# Generated by Django 2.1 on 2018-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
