# Generated by Django 2.1 on 2018-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0002_village_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='fanatic',
            field=models.IntegerField(default=0),
        ),
    ]
