# Generated by Django 2.1 on 2018-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0003_village_fanatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
