# Generated by Django 2.1 on 2018-09-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0004_auto_20180917_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='bomber',
        ),
    ]
