# Generated by Django 2.1 on 2018-09-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0005_remove_village_bomber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='citizen',
            field=models.IntegerField(default=0, verbose_name='市民'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=40, verbose_name='村名'),
        ),
    ]
