# Generated by Django 2.1 on 2018-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0006_auto_20180923_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='lover',
            field=models.IntegerField(default=0, verbose_name='恋人'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ability',
            field=models.CharField(max_length=200, verbose_name='能力'),
        ),
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.CharField(max_length=200, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='character',
            name='condition',
            field=models.CharField(max_length=200, verbose_name='勝つ条件'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=40, verbose_name='キャラ名'),
        ),
        migrations.AlterField(
            model_name='village',
            name='aristcracy',
            field=models.IntegerField(default=0, verbose_name='貴族'),
        ),
        migrations.AlterField(
            model_name='village',
            name='assassin',
            field=models.IntegerField(default=0, verbose_name='暗殺者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='bakery',
            field=models.IntegerField(default=0, verbose_name='パン屋'),
        ),
        migrations.AlterField(
            model_name='village',
            name='bat',
            field=models.IntegerField(default=0, verbose_name='コウモリ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='big_wolf',
            field=models.IntegerField(default=0, verbose_name='大狼'),
        ),
        migrations.AlterField(
            model_name='village',
            name='black_cat',
            field=models.IntegerField(default=0, verbose_name='黒猫'),
        ),
        migrations.AlterField(
            model_name='village',
            name='category',
            field=models.CharField(max_length=200, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='village',
            name='cursed',
            field=models.IntegerField(default=0, verbose_name='呪われし者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='description',
            field=models.CharField(max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='village',
            name='dictator',
            field=models.IntegerField(default=0, verbose_name='独裁者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='doctor',
            field=models.IntegerField(default=0, verbose_name='医者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='dspcho',
            field=models.IntegerField(default=0, verbose_name='狂人'),
        ),
        migrations.AlterField(
            model_name='village',
            name='f_teller',
            field=models.IntegerField(default=0, verbose_name='占い師'),
        ),
        migrations.AlterField(
            model_name='village',
            name='fanatic',
            field=models.IntegerField(default=0, verbose_name='狂信者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='fox',
            field=models.IntegerField(default=0, verbose_name='妖狐'),
        ),
        migrations.AlterField(
            model_name='village',
            name='fugitive',
            field=models.IntegerField(default=0, verbose_name='逃亡者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='goyoku',
            field=models.IntegerField(default=0, verbose_name='強欲な人狼'),
        ),
        migrations.AlterField(
            model_name='village',
            name='hunter',
            field=models.IntegerField(default=0, verbose_name='狩人'),
        ),
        migrations.AlterField(
            model_name='village',
            name='level',
            field=models.IntegerField(default=0, verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='village',
            name='martydom',
            field=models.IntegerField(default=0, verbose_name='殉教者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='mayor',
            field=models.IntegerField(default=0, verbose_name='市民'),
        ),
        migrations.AlterField(
            model_name='village',
            name='nekomata',
            field=models.IntegerField(default=0, verbose_name='猫又'),
        ),
        migrations.AlterField(
            model_name='village',
            name='people',
            field=models.IntegerField(default=0, verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='village',
            name='pigman',
            field=models.IntegerField(default=0, verbose_name='豚男'),
        ),
        migrations.AlterField(
            model_name='village',
            name='psyco',
            field=models.IntegerField(default=0, verbose_name='サイコ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='queen',
            field=models.IntegerField(default=0, verbose_name='女王'),
        ),
        migrations.AlterField(
            model_name='village',
            name='santa',
            field=models.IntegerField(default=0, verbose_name='サンタ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='sasaki',
            field=models.IntegerField(default=0, verbose_name='ささやく狂人'),
        ),
        migrations.AlterField(
            model_name='village',
            name='shaman',
            field=models.IntegerField(default=0, verbose_name='霊能者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='slave',
            field=models.IntegerField(default=0, verbose_name='奴隷'),
        ),
        migrations.AlterField(
            model_name='village',
            name='sorcerer',
            field=models.IntegerField(default=0, verbose_name='妖術師'),
        ),
        migrations.AlterField(
            model_name='village',
            name='straw_doll',
            field=models.IntegerField(default=0, verbose_name='わら人形'),
        ),
        migrations.AlterField(
            model_name='village',
            name='teruteru',
            field=models.IntegerField(default=0, verbose_name='てるてる坊主'),
        ),
        migrations.AlterField(
            model_name='village',
            name='thief',
            field=models.IntegerField(default=0, verbose_name='怪盗'),
        ),
        migrations.AlterField(
            model_name='village',
            name='trap_nurses',
            field=models.IntegerField(default=0, verbose_name='罠師'),
        ),
        migrations.AlterField(
            model_name='village',
            name='werewolf',
            field=models.IntegerField(default=0, verbose_name='人狼'),
        ),
        migrations.AlterField(
            model_name='village',
            name='wiseman',
            field=models.IntegerField(default=0, verbose_name='賢者'),
        ),
        migrations.AlterField(
            model_name='village',
            name='wisewolf',
            field=models.IntegerField(default=0, verbose_name='賢狼'),
        ),
        migrations.AlterField(
            model_name='village',
            name='wolfboy',
            field=models.IntegerField(default=0, verbose_name='狼少年'),
        ),
        migrations.AlterField(
            model_name='village',
            name='zombi',
            field=models.IntegerField(default=0, verbose_name='ゾンビ'),
        ),
    ]
