# Generated by Django 2.1 on 2018-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinromura', '0008_auto_20181001_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='noisywolf',
            field=models.IntegerField(default=0, verbose_name='饒舌な人狼'),
        ),
    ]
